//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTest1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Model { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public Nullable<int> ManufacturerID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<int> Number { get; set; }
        public byte[] ProductImage { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
    }
}
